openapi: 3.0.1
info:
  title: Employee Service
  description: Employee CRUD API.
  version: 1.0.0
servers:
- url: /v2
paths:
  /employees:
    get:
      summary: Get Employees
      operationId: getEmployee
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
    post:
      summary: Add an Employee
      operationId: addEmployee
      requestBody:
        description: Employee to be added 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Employee'
        required: true
      responses:
        200:
          description: Employee Added
          content:
            application/json:
              schema:
                type: string
        422:
          description: Employee Could Not be added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: employee
components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: John
        designation:
          type: string
          example: Manager
